DROP TABLE IF EXISTS itemstable;
CREATE TABLE itemstable (
	Item_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	L_ID int NOT NULL,
	Name varchar(50) NOT NULL,
	FOREIGN KEY (L_ID) REFERENCES liststable(ID) ON DELETE CASCADE
);
